### ISSUE TITLE
Catch 22

### ISSUE THREAD

**Issue by joe-adams** [mark-vieira/gradle-maven-settings-plugin#4]
The problem is that even if we put this plugin in our repository, we can't get to the repository without this plugin...

Can you make it available as a .jar that you can put in your buildSrc or something like that?  I'm trying to put source of this into my buildSrc, but that doesn't work because it can't resolve the dependencies.

**Comment by mark-vieira** [comment]
You can download the JAR strait from the plugin portal [here](https://plugins.gradle.org/m2/net/linguica/gradle/maven-settings-plugin/0.5/maven-settings-plugin-0.5.jar). You can then just add the JAR itself to the buildscript classpath:

buildscript {
    classpath files('path/to/maven-settings-plugin-0.5.jar')
}

Keep in mind the plugin itself has dependencies as well so you'll need to explicitly download those as well and add them to the classpath.

https://github.com/mark-vieira/gradle-maven-settings-plugin/blob/master/build.gradle#L17-L23
