### ISSUE TITLE
Bump project version to next snapshot

### ISSUE THREAD

**Issue by sslavic** [mark-vieira/gradle-maven-settings-plugin#6]
https://github.com/mark-vieira/gradle-maven-settings-plugin/blob/master/gradle.properties#L2 is currently 0.5-SNAPSHOT although 0.5 version has been released. Please bump it to 0.6-SNAPSHOT or similar. Consider also automating this as part of the release process.

**Comment by mark-vieira** [comment]
Done. Yes, release automation could use some work. Right now this is manual given how infrequently I release.
