### ISSUE TITLE
Is SSH supported for repository resolution?

### ISSUE THREAD

**Issue by mrollo** [mark-vieira/gradle-maven-settings-plugin#8]
[maven settings](https://maven.apache.org/settings.html
) allows for configuring ssh authentication (key file, passphrase). Can gradle use this to resolve dependencies that are only available via SSH?

**Comment by mark-vieira** [comment]
Unfortunately no, as Gradle does not currently support authenticating to SFTP repositories via private key and passphrase. Only username/password authentication is supported.
